# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js Backend Tests

on:
  push:
    branches:
     - main
    paths:
     - 'backend/**'
  pull_request:
    branches:
     - main
    paths:
     - 'backend/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      working-directory: ./backend
      run: npm install

    - name: Setup environment secrets
      working-directory: ./backend
      run: |
        echo "BASE_URL: ${{ secrets.BASE_URL }}" >> .env.development
        echo "PORT: ${{ secrets.PORT }}" >> .env.development
        echo "NODE_ENV: ${{ secrets.NODE_ENV }}" >> .env.development
        echo "JWT_SECRET: ${{ secrets.JWT_SECRET }}" >> .env.development
        echo "MONGO_URI: ${{ secrets.MONGO_URI }}" >> .env.development

    - name: Run tests
      working-directory: ./backend
      run: npm run test
